################################################################################
# Hello 1
################################################################################
apiVersion: v1
kind: Service
metadata:
  name: hello-1
  labels:
    app: hello-1
    service: hello-1
spec:
  selector:
    app: hello-1
  ports:
  - port: 8080
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-1-v1
  labels:
    app: hello-1
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-1
      version: v1
  template:
    metadata:
      labels:
        app: hello-1
        version: v1
    spec:
      containers:
      - name: hello-1
        image: hello:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          value: "hello-1"
        - name: UPSTREAM_HOST
          value: "hello-2:8080"
---
################################################################################
# Hello 2
################################################################################
apiVersion: v1
kind: Service
metadata:
  name: hello-2
  labels:
    app: hello-2
    service: hello-2
spec:
  selector:
    app: hello-2
  ports:
  - port: 8080
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-2-v1
  labels:
    app: hello-2
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-2
      version: v1
  template:
    metadata:
      labels:
        app: hello-2
        version: v1
    spec:
      containers:
      - name: hello-2
        image: hello:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          value: "hello-2"
---
