---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_NAME}
  labels:
    stack: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APP_NAME}
  template:
    metadata:
      labels:
        app: ${APP_NAME}
    spec:
      containers:
      - name: ${APP_NAME}
        image: hello:latest
        imagePullPolicy: Never
        env:
        - name: MESSAGE
          value: "${APP_NAME}"
        - name: PORT
          value: "8080"
        - name: UPSTREAM_URL
          value: ${UPSTREAM_URL}
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}
  labels:
    stack: hello
spec:
  type: NodePort
  selector:
    app: ${APP_NAME}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
