# Hello 2 feature
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-2-v2
  labels:
    app: hello-2
    version: v2
    "devenv/version": v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-2
      version: v2
  template:
    metadata:
      labels:
        app: hello-2
        version: v2
    spec:
      containers:
        - name: hello-2
          image: hello:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: MESSAGE
              value: "hello-2 from v2"
