apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: devenv-control-role
rules:
  - apiGroups: [""]
    resources: ["namespace", "services"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["networking.istio.io"]
    resources: ["virtualservices", "destinationrules"]
    verbs: ["get", "list"]
