apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: devenv-mesh-controller-crb
subjects:
  - kind: ServiceAccount
    name: default
    namespace: devenv
roleRef:
  kind: ClusterRole
  name: devenv-mesh-controller-role
  apiGroup: rbac.authorization.k8s.io
