apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: pod-label-validator
webhooks:
  - name: pod-label.validator.example.com
    sideEffects: NoneOnDryRun
    namespaceSelector:
      matchExpressions:
        - key: runlevel
          operator: NotIn
          values: ["0", "1"]
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values: ["devenv"]
    admissionReviewVersions: ["v1", "v1beta1"]
    clientConfig:
      service:
        name: admission-controller
        namespace: devenv
        path: "/validate"
      caBundle: ${CA_BUNDLE}
    rules:
      - apiGroups: ["apps"]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["deployments"]
        scope: "Namespaced"
    failurePolicy: Fail
    matchPolicy: Equivalent
