# Hello 1 feature
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-1-v2
  labels:
    app: hello-1
    version: v2
    "devenv/version": v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-1
      version: v2
  template:
    metadata:
      labels:
        app: hello-1
        version: v2
    spec:
      containers:
        - name: hello-1
          image: hello:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: MESSAGE
              value: "hello-1 from v2"
            - name: UPSTREAM_HOST
              value: "hello-2:8080"
